server:
  port: 9192
spring:
  h2:
    console:
      enabled: true  
  application:
    name: ORDER-SERVICE   
  cloud:
    config:
      import-check:
        enabled: false  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  
    
#ELK
logging:
  file: /home/mfoum/backup/Dossier/Project_spring/1Microservice_ELK/logs/microservice.log     

      